# Generated by Django 3.0.8 on 2020-10-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0002_auto_20201004_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofile',
            name='image',
            field=models.ImageField(blank=True, default='UserControl/images/avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
