# Generated by Django 3.0.8 on 2020-10-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserControl', '0003_auto_20201006_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
